# 需要配置指定参数
version: '2.1'
services:
  "php":
    volumes:
      - "${compose_volumes_php_conf}"
      - "${compose_volumes_php_etc}"
    volumes_from: 
      - base
    extends:
      file: "docker-compose-full.yml"
      service: "php"
    # 在virtualBox时出现无法连接外网的情况
    dns: '8.8.8.8'
    networks:
      all:
        aliases: 
          - php

  "nginx":
    volumes:
      - "${compose_volumes_nginx}"
    volumes_from: 
      - base
    # 在virtualBox时出现无法连接外网的情况
    dns: '8.8.8.8'
    extends:
      file: "docker-compose-full.yml"
      service: "nginx"

  base:
    volumes:
      - "${compose_volumes_base}"
    extends:
      file: "docker-compose-full.yml"
      service: "base"

networks:
  all: {}